cdef convert_to_array_dict(data)
cdef concatenate_dicts_or_arrays(dict_list_of_arrays)
cdef char** to_cstring_array(list str_list)
cdef int* to_cint_array(list int_list)
cdef float* to_cfloat_array(list float_list)
cdef long long* to_clong_array(long_list)